import type {
  AmbitoEvaluacion,
  CategoriaHallazgoV2,
  Criticidad,
  ModuloPreguntasV2,
  TipoEvento,
} from "./types";

export type EntradaDiccionarioHallazgoV2 = {
  categoria: CategoriaHallazgoV2;
  familia: string;
  ambitoSugerido: AmbitoEvaluacion;
  ambitosSecundariosSugeridos?: AmbitoEvaluacion[];
  tipoEventoSugerido: TipoEvento;
  moduloPreguntasSugerido: ModuloPreguntasV2;
  criticidadBaseSugerida: Criticidad;
  topeCriticidad: Criticidad;
  prioridad?: number;
  palabrasClave: string[];
  sinonimos?: string[];
  frasesFrecuentes?: string[];
  exclusiones?: string[];
  senalesElevanCriticidad?: string[];
  senalesPermitenCritico?: string[];
  normativaProbable?: string[];
  requiereRevisionManual?: boolean;
};

export const DICCIONARIO_HALLAZGOS_V2: EntradaDiccionarioHallazgoV2[] = [
  {
    categoria: "orden_aseo_objeto_fuera_lugar",
    familia: "Orden, aseo y objetos fuera de lugar",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "orden_aseo_objeto_fuera_lugar",
    criticidadBaseSugerida: "BAJO",
    topeCriticidad: "MEDIO",
    prioridad: 3,
    palabrasClave: ["maleta", "bolso", "mochila", "caja", "desorden", "orden y aseo", "objeto fuera de lugar"],
    sinonimos: ["elemento abandonado", "herramienta fuera de lugar", "material en pasillo", "obstaculo menor"],
    frasesFrecuentes: ["maleta abierta", "objeto en area de trabajo", "material fuera de lugar"],
    exclusiones: ["salida de emergencia bloqueada", "via de evacuacion bloqueada", "carga suspendida"],
    senalesElevanCriticidad: ["Obstruye transito activo.", "Puede provocar caida al mismo nivel."],
    senalesPermitenCritico: ["Bloqueo efectivo de via de evacuacion con personas expuestas."],
    normativaProbable: ["Gestion preventiva general"],
  },
  {
    categoria: "transito_caida_mismo_nivel",
    familia: "Transito peatonal y caida al mismo nivel",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "transito_caida_mismo_nivel",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 5,
    palabrasClave: ["piso mojado", "superficie resbaladiza", "desnivel", "tropiezo", "caida al mismo nivel", "transito peatonal"],
    sinonimos: ["pasillo obstruido", "ruta peatonal", "circulacion", "resbalon"],
    frasesFrecuentes: ["zona de transito", "paso peatonal bloqueado", "riesgo de tropiezo"],
    exclusiones: ["caida de altura", "altura sin arnes"],
    senalesElevanCriticidad: ["Transito activo.", "Sin senalizacion o segregacion."],
    senalesPermitenCritico: ["Caida con consecuencia grave ya ocurrida o condicion masiva sin control."],
    normativaProbable: ["Ley 16.744", "DS 44"],
  },
  {
    categoria: "caida_altura",
    familia: "Caida de altura",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "caida_altura",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 10,
    palabrasClave: ["altura", "arnes", "linea de vida", "andamio", "escalera", "borde", "techumbre", "plataforma"],
    sinonimos: ["proteccion contra caidas", "trabajo en altura", "baranda", "punto de anclaje"],
    frasesFrecuentes: ["altura sin arnes", "trabajo en altura sin proteccion", "borde abierto"],
    exclusiones: ["altura administrativa", "altura de documento"],
    senalesElevanCriticidad: ["Trabajo en ejecucion.", "Proteccion parcial o inexistente."],
    senalesPermitenCritico: ["Persona expuesta a caida de altura sin proteccion efectiva."],
    normativaProbable: ["Ley 16.744", "DS 44"],
  },
  {
    categoria: "electrico",
    familia: "Energia electrica",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "electrico",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 10,
    palabrasClave: ["cable", "energizado", "tablero", "enchufe", "extension", "electricidad", "conductor expuesto"],
    sinonimos: ["fase", "chispa", "cortocircuito", "energia electrica", "desenergizar", "bloqueo electrico"],
    frasesFrecuentes: ["cable energizado", "conductor expuesto", "tablero abierto"],
    exclusiones: ["cable de datos sin energia", "cable ordenado"],
    senalesElevanCriticidad: ["Elemento energizado.", "Personas con acceso directo."],
    senalesPermitenCritico: ["Energia peligrosa expuesta o no controlada."],
    normativaProbable: ["Ley 16.744", "DS 44"],
  },
  {
    categoria: "maquinaria_equipos",
    familia: "Maquinaria y partes moviles",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "maquinaria_equipos",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 8,
    palabrasClave: ["maquina", "maquinaria", "resguardo", "atrapamiento", "parte movil", "guardas"],
    sinonimos: ["equipo sin resguardo", "equipo danado", "zona de atrapamiento", "punto de pellizco"],
    frasesFrecuentes: ["maquinaria sin resguardo", "parte movil expuesta"],
    exclusiones: ["operacion equipo sin falla", "equipo de oficina"],
    senalesElevanCriticidad: ["Equipo operando.", "Acceso a parte movil."],
    senalesPermitenCritico: ["Parte movil expuesta con personas al alcance."],
    normativaProbable: ["Ley 16.744", "DS 44"],
  },
  {
    categoria: "herramientas_equipos",
    familia: "Herramientas y equipos",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "herramientas_equipos",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 6,
    palabrasClave: ["herramienta defectuosa", "equipo defectuoso", "esmeril", "taladro", "sierra", "herramienta danada"],
    sinonimos: ["herramienta hechiza", "cable herramienta", "disco de corte", "equipo portatil"],
    frasesFrecuentes: ["herramienta en mal estado", "equipo sin mantencion"],
    exclusiones: ["herramienta fuera de lugar"],
    senalesElevanCriticidad: ["Uso en ejecucion.", "Falta de proteccion o mantencion."],
    senalesPermitenCritico: ["Herramienta energizada o de corte con exposicion directa grave."],
    normativaProbable: ["Ley 16.744", "DS 44"],
  },
  {
    categoria: "izaje_carga_suspendida",
    familia: "Izaje y carga suspendida",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "izaje_carga_suspendida",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 10,
    palabrasClave: ["grua", "izaje", "carga suspendida", "eslinga", "estrobo", "maniobra", "rigger"],
    sinonimos: ["aparejo", "puente grua", "levante", "carga izada"],
    frasesFrecuentes: ["persona bajo carga", "carga suspendida sobre transito"],
    exclusiones: ["carga almacenada", "carga documental"],
    senalesElevanCriticidad: ["Carga suspendida.", "Zona sin segregacion."],
    senalesPermitenCritico: ["Personas bajo carga suspendida o maniobra sin control."],
    normativaProbable: ["Ley 16.744", "DS 44"],
  },
  {
    categoria: "excavaciones",
    familia: "Excavaciones",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "excavaciones",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 9,
    palabrasClave: ["excavacion", "zanja", "talud", "entibacion", "derrumbe", "socavon"],
    sinonimos: ["calicata", "corte de terreno", "borde excavacion"],
    frasesFrecuentes: ["zanja sin proteccion", "excavacion sin entibacion"],
    exclusiones: ["excavacion documental"],
    senalesElevanCriticidad: ["Profundidad relevante.", "Borde sin proteccion."],
    senalesPermitenCritico: ["Riesgo de derrumbe con personas expuestas."],
    normativaProbable: ["Ley 16.744", "DS 44"],
  },
  {
    categoria: "espacios_confinados",
    familia: "Espacios confinados",
    ambitoSugerido: "seguridad_laboral",
    ambitosSecundariosSugeridos: ["salud_ocupacional"],
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "espacios_confinados",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 10,
    palabrasClave: ["espacio confinado", "atmosfera peligrosa", "medicion de gases", "ingreso confinado"],
    sinonimos: ["tanque", "camara", "pozo", "recinto confinado"],
    frasesFrecuentes: ["ingreso a espacio confinado", "sin medicion de gases"],
    exclusiones: ["bodega amplia"],
    senalesElevanCriticidad: ["Ingreso en ejecucion.", "Sin medicion o permiso."],
    senalesPermitenCritico: ["Ingreso a espacio confinado sin controles criticos."],
    normativaProbable: ["Ley 16.744", "DS 44", "DS 594"],
    requiereRevisionManual: true,
  },
  {
    categoria: "sustancias_peligrosas",
    familia: "Sustancias peligrosas",
    ambitoSugerido: "medio_ambiente",
    ambitosSecundariosSugeridos: ["salud_ocupacional"],
    tipoEventoSugerido: "aspecto_ambiental",
    moduloPreguntasSugerido: "sustancias_peligrosas",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 8,
    palabrasClave: ["acido", "solvente", "pintura", "combustible", "inflamable", "corrosivo", "toxico", "gas", "cilindro", "quimico"],
    sinonimos: ["sustancia peligrosa", "hoja de seguridad", "hds", "sds", "rotulacion", "sin rotulacion"],
    frasesFrecuentes: ["sustancia quimica sin rotulacion", "envase sin etiqueta"],
    exclusiones: ["sin derrame", "ni fuga"],
    senalesElevanCriticidad: ["Envase danado.", "Exposicion de personas."],
    senalesPermitenCritico: ["Liberacion no controlada con exposicion o medio receptor."],
    normativaProbable: ["DS 594", "Ley 19.300", "Normativa de sustancias peligrosas aplicable"],
  },
  {
    categoria: "derrame_fuga",
    familia: "Derrames y fugas",
    ambitoSugerido: "medio_ambiente",
    ambitosSecundariosSugeridos: ["salud_ocupacional"],
    tipoEventoSugerido: "aspecto_ambiental",
    moduloPreguntasSugerido: "derrame_fuga",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "CRITICO",
    prioridad: 12,
    palabrasClave: ["derrame", "fuga", "filtracion", "goteo", "liquido", "aceite", "combustible", "mancha", "escurrimiento"],
    sinonimos: ["perdida de fluido", "quimico derramado", "hidrocarburo"],
    frasesFrecuentes: ["derrame de aceite", "derrame hacia suelo", "derrame a alcantarillado", "fuga sin control"],
    exclusiones: ["sin derrame", "ni fuga"],
    senalesElevanCriticidad: ["No contenido.", "Sustancia peligrosa.", "Exposicion de personas."],
    senalesPermitenCritico: ["Llegada real o probable a suelo, agua, drenaje o alcantarillado."],
    normativaProbable: ["Ley 19.300", "Normativa de sustancias peligrosas aplicable"],
  },
  {
    categoria: "residuos",
    familia: "Residuos",
    ambitoSugerido: "medio_ambiente",
    tipoEventoSugerido: "aspecto_ambiental",
    moduloPreguntasSugerido: "residuos",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 7,
    palabrasClave: ["residuo", "basura", "contenedor", "segregacion", "residuo peligroso", "envase contaminado", "disposicion"],
    sinonimos: ["retiro de residuos", "acopio", "respel", "residuo industrial"],
    frasesFrecuentes: ["residuo mal segregado", "contenedor sin rotulo"],
    exclusiones: ["basura domestica menor sin exposicion"],
    senalesElevanCriticidad: ["Residuo peligroso.", "Exposicion o liberacion."],
    senalesPermitenCritico: ["Residuo peligroso liberado o con exposicion significativa."],
    normativaProbable: ["Ley 19.300", "Normativa de residuos aplicable"],
  },
  {
    categoria: "emisiones_polvo_humos",
    familia: "Emisiones atmosfericas, polvo y humos",
    ambitoSugerido: "salud_ocupacional",
    ambitosSecundariosSugeridos: ["medio_ambiente"],
    tipoEventoSugerido: "aspecto_ambiental",
    moduloPreguntasSugerido: "emisiones_polvo_humos",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 7,
    palabrasClave: ["polvo", "humo", "emision", "gases", "material particulado", "silice"],
    sinonimos: ["polucion", "nube de polvo", "ventilacion deficiente"],
    frasesFrecuentes: ["polvo visible sin control", "emision de humo"],
    exclusiones: ["polvo domestico menor"],
    senalesElevanCriticidad: ["Trabajadores expuestos.", "Sin control de ventilacion o humectacion."],
    senalesPermitenCritico: ["Exposicion aguda severa o atmosfera peligrosa confirmada."],
    normativaProbable: ["DS 594", "Ley 19.300", "Normativa de emisiones aplicable"],
  },
  {
    categoria: "ruido_agentes_fisicos",
    familia: "Ruido y agentes fisicos",
    ambitoSugerido: "salud_ocupacional",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "ruido_agentes_fisicos",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 6,
    palabrasClave: ["ruido", "vibracion", "calor", "frio", "radiacion", "iluminacion"],
    sinonimos: ["estres termico", "exposicion fisica", "dosimetria", "medicion higienica"],
    frasesFrecuentes: ["ruido elevado", "sin proteccion auditiva"],
    exclusiones: ["ruido administrativo menor"],
    senalesElevanCriticidad: ["Exposicion directa.", "Sin EPP o control."],
    senalesPermitenCritico: ["Exposicion aguda severa con dano inmediato probable."],
    normativaProbable: ["DS 594", "Normativa de ruido aplicable"],
  },
  {
    categoria: "exposicion_quimica",
    familia: "Exposicion quimica",
    ambitoSugerido: "salud_ocupacional",
    ambitosSecundariosSugeridos: ["medio_ambiente"],
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "exposicion_quimica",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "CRITICO",
    prioridad: 8,
    palabrasClave: ["vapor", "gas", "aerosol", "inhalacion", "contacto quimico", "exposicion quimica"],
    sinonimos: ["olor fuerte", "emanacion", "neblina quimica"],
    frasesFrecuentes: ["trabajador expuesto a quimico", "sin proteccion respiratoria"],
    exclusiones: ["quimico almacenado sin exposicion"],
    senalesElevanCriticidad: ["Exposicion directa.", "Sustancia peligrosa."],
    senalesPermitenCritico: ["Exposicion aguda no controlada a sustancia de alta peligrosidad."],
    normativaProbable: ["DS 594", "Normativa de sustancias peligrosas aplicable"],
  },
  {
    categoria: "exposicion_biologica",
    familia: "Exposicion biologica",
    ambitoSugerido: "salud_ocupacional",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "exposicion_biologica",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 6,
    palabrasClave: ["biologico", "hongos", "bacteria", "aguas servidas", "material biologico", "plaga"],
    sinonimos: ["contaminacion biologica", "residuo biologico", "excretas"],
    frasesFrecuentes: ["contacto con aguas servidas", "exposicion biologica"],
    exclusiones: ["referencia biologica teorica"],
    senalesElevanCriticidad: ["Contacto directo.", "Sin EPP o higiene."],
    senalesPermitenCritico: ["Exposicion masiva o agente biologico severo confirmado."],
    normativaProbable: ["DS 594"],
    requiereRevisionManual: true,
  },
  {
    categoria: "incendio_emergencia",
    familia: "Incendio y emergencia",
    ambitoSugerido: "emergencia",
    tipoEventoSugerido: "emergencia",
    moduloPreguntasSugerido: "incendio_emergencia",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 9,
    palabrasClave: ["incendio", "fuego", "amago", "explosion", "extintor", "red humeda", "alarma", "emergencia"],
    sinonimos: ["combustion", "chispa", "material combustible", "equipo de emergencia"],
    frasesFrecuentes: ["extintor obstruido", "amago de incendio"],
    exclusiones: ["simulacro controlado"],
    senalesElevanCriticidad: ["Fuente de ignicion activa.", "Equipo de emergencia no disponible."],
    senalesPermitenCritico: ["Fuego, explosion o atmosfera peligrosa activa."],
    normativaProbable: ["Ley 16.744", "DS 44", "DS 594"],
  },
  {
    categoria: "evacuacion",
    familia: "Vias de evacuacion",
    ambitoSugerido: "emergencia",
    tipoEventoSugerido: "emergencia",
    moduloPreguntasSugerido: "evacuacion",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 10,
    palabrasClave: ["salida emergencia", "salida de emergencia", "via evacuacion", "via de evacuacion", "ruta evacuacion", "puerta emergencia"],
    sinonimos: ["escape", "pasillo emergencia", "acceso bloqueado"],
    frasesFrecuentes: ["salida de emergencia bloqueada", "ruta de evacuacion obstruida"],
    exclusiones: ["ruta libre", "sin bloqueo"],
    senalesElevanCriticidad: ["Ruta obstruida.", "Ocupantes presentes."],
    senalesPermitenCritico: ["Bloqueo efectivo de salida o ruta de evacuacion sin alternativa."],
    normativaProbable: ["Ley 16.744", "DS 44", "DS 594"],
  },
  {
    categoria: "senalizacion",
    familia: "Senalizacion",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "senalizacion",
    criticidadBaseSugerida: "BAJO",
    topeCriticidad: "MEDIO",
    prioridad: 4,
    palabrasClave: ["senalizacion", "letrero", "cartel", "demarcacion", "barrera", "cinta de peligro"],
    sinonimos: ["senal", "aviso", "rotulo de seguridad"],
    frasesFrecuentes: ["sin senalizacion", "demarcacion insuficiente"],
    exclusiones: ["senalizacion correcta"],
    senalesElevanCriticidad: ["Asociada a peligro activo.", "Zona de transito."],
    senalesPermitenCritico: ["Ausencia de senalizacion en riesgo critico activo."],
    normativaProbable: ["Ley 16.744", "DS 44"],
  },
  {
    categoria: "elementos_proteccion_personal",
    familia: "Elementos de proteccion personal",
    ambitoSugerido: "seguridad_laboral",
    ambitosSecundariosSugeridos: ["salud_ocupacional"],
    tipoEventoSugerido: "acto_inseguro",
    moduloPreguntasSugerido: "elementos_proteccion_personal",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 7,
    palabrasClave: ["epp", "casco", "guantes", "lentes", "proteccion auditiva", "respirador", "arnes"],
    sinonimos: ["sin epp", "proteccion personal", "equipo de proteccion"],
    frasesFrecuentes: ["trabajador sin epp", "sin proteccion auditiva", "sin respirador"],
    exclusiones: ["epp disponible y usado"],
    senalesElevanCriticidad: ["Exposicion directa al agente.", "Actividad en ejecucion."],
    senalesPermitenCritico: ["Falta de EPP frente a riesgo fatal o energia critica activa."],
    normativaProbable: ["Ley 16.744", "DS 44", "DS 594"],
  },
  {
    categoria: "procedimientos_ast_permisos",
    familia: "Procedimientos, AST, PTS, PTP y permisos",
    ambitoSugerido: "legal_documental",
    ambitosSecundariosSugeridos: ["seguridad_laboral"],
    tipoEventoSugerido: "desviacion_legal_documental",
    moduloPreguntasSugerido: "procedimientos_ast_permisos",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "CRITICO",
    prioridad: 11,
    palabrasClave: [
      "procedimiento",
      "permiso",
      "ast",
      "pts",
      "ptp",
      "sin ast",
      "sin pts",
      "sin permiso",
      "falta ast",
      "falta pts",
      "falta permiso",
    ],
    sinonimos: [
      "procedimiento faltante",
      "permiso vencido",
      "analisis seguro",
      "trabajo critico sin permiso",
      "falta de ast",
      "falta de pts",
    ],
    frasesFrecuentes: [
      "sin ast para trabajo en altura",
      "falta ast para trabajo en altura",
      "falta de ast para trabajo en altura",
      "permiso no vigente",
      "pts faltante",
    ],
    exclusiones: ["permiso vigente", "ast completo"],
    senalesElevanCriticidad: ["Actividad critica en ejecucion.", "Personas expuestas."],
    senalesPermitenCritico: ["Falta documental habilita trabajo critico con exposicion real."],
    normativaProbable: ["DS 44"],
    requiereRevisionManual: true,
  },
  {
    categoria: "induccion_capacitacion_autorizacion",
    familia: "Induccion, capacitacion y autorizacion",
    ambitoSugerido: "legal_documental",
    ambitosSecundariosSugeridos: ["seguridad_laboral"],
    tipoEventoSugerido: "desviacion_legal_documental",
    moduloPreguntasSugerido: "induccion_capacitacion_autorizacion",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 6,
    palabrasClave: ["induccion", "capacitacion", "autorizacion", "certificado", "competencia", "licencia"],
    sinonimos: ["sin induccion", "sin capacitacion", "operador no autorizado"],
    frasesFrecuentes: ["trabajador sin induccion", "operador sin autorizacion"],
    exclusiones: ["capacitacion vigente", "autorizado"],
    senalesElevanCriticidad: ["Ejecuta tarea critica.", "Sin competencia verificada."],
    senalesPermitenCritico: ["Persona no autorizada ejecutando tarea critica con exposicion grave."],
    normativaProbable: ["DS 44"],
    requiereRevisionManual: true,
  },
  {
    categoria: "documentos_legales_preventivos",
    familia: "Documentos legales/preventivos",
    ambitoSugerido: "legal_documental",
    tipoEventoSugerido: "desviacion_legal_documental",
    moduloPreguntasSugerido: "documentos_legales_preventivos",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "MEDIO",
    prioridad: 5,
    palabrasClave: ["documento", "documental", "registro", "matriz", "plan", "programa", "acta"],
    sinonimos: ["documento faltante", "registro faltante", "matriz no actualizada"],
    frasesFrecuentes: ["falta registro", "documentacion incompleta"],
    exclusiones: ["documento vigente", "registro completo"],
    senalesElevanCriticidad: ["Documento habilita control operacional."],
    senalesPermitenCritico: ["Solo permite CRITICO si habilita trabajo critico con exposicion real."],
    normativaProbable: ["DS 44"],
    requiereRevisionManual: true,
  },
  {
    categoria: "legal_documental",
    familia: "Legal/documental general",
    ambitoSugerido: "legal_documental",
    tipoEventoSugerido: "desviacion_legal_documental",
    moduloPreguntasSugerido: "legal_documental",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "MEDIO",
    prioridad: 4,
    palabrasClave: ["documentacion", "cumplimiento", "norma", "legal", "auditoria"],
    sinonimos: ["brecha documental", "incumplimiento documental"],
    frasesFrecuentes: ["hallazgo documental", "desviacion legal"],
    exclusiones: ["sin brecha documental"],
    senalesElevanCriticidad: ["Relacion con actividad riesgosa."],
    senalesPermitenCritico: ["Incumplimiento documental con actividad critica activa y exposicion."],
    normativaProbable: ["DS 44"],
    requiereRevisionManual: true,
  },
  {
    categoria: "aspectos_ambientales",
    familia: "Aspectos ambientales",
    ambitoSugerido: "medio_ambiente",
    tipoEventoSugerido: "aspecto_ambiental",
    moduloPreguntasSugerido: "aspectos_ambientales",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 5,
    palabrasClave: ["aspecto ambiental", "suelo", "agua", "aire", "flora", "fauna", "alcantarillado", "cauce"],
    sinonimos: ["medio receptor", "condicion ambiental", "riesgo ambiental"],
    frasesFrecuentes: ["posible aspecto ambiental", "riesgo de afectacion ambiental"],
    exclusiones: ["sin aspecto ambiental"],
    senalesElevanCriticidad: ["Medio receptor cercano.", "Control parcial."],
    senalesPermitenCritico: ["Impacto real o liberacion no controlada."],
    normativaProbable: ["Ley 19.300"],
  },
  {
    categoria: "impactos_ambientales_reales",
    familia: "Impactos ambientales reales",
    ambitoSugerido: "medio_ambiente",
    tipoEventoSugerido: "impacto_ambiental",
    moduloPreguntasSugerido: "impactos_ambientales_reales",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 9,
    palabrasClave: ["impacto ambiental", "contaminacion", "afecto suelo", "afecto agua", "muerte fauna", "descarga"],
    sinonimos: ["dano ambiental", "medio receptor afectado", "contaminacion de suelo", "contaminacion de agua"],
    frasesFrecuentes: ["llego a cauce", "descarga a alcantarillado", "contamino suelo"],
    exclusiones: ["riesgo sin impacto confirmado"],
    senalesElevanCriticidad: ["Impacto real confirmado.", "Afectacion de medio receptor."],
    senalesPermitenCritico: ["Impacto no contenido con obligacion de contencion o notificacion."],
    normativaProbable: ["Ley 19.300", "Normativa de aguas aplicable", "Normativa de suelo aplicable"],
    requiereRevisionManual: true,
  },
  {
    categoria: "ambiental_general",
    familia: "Ambiental general",
    ambitoSugerido: "medio_ambiente",
    tipoEventoSugerido: "aspecto_ambiental",
    moduloPreguntasSugerido: "ambiental_general",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 3,
    palabrasClave: ["ambiental", "ambiente", "gestion ambiental"],
    sinonimos: ["condicion ambiental general"],
    frasesFrecuentes: ["hallazgo ambiental"],
    exclusiones: ["sin relacion ambiental"],
    senalesElevanCriticidad: ["Medio receptor o sustancia involucrada."],
    senalesPermitenCritico: ["Impacto ambiental real no controlado."],
    normativaProbable: ["Ley 19.300"],
  },
  {
    categoria: "comunidad_terceros",
    familia: "Comunidad/terceros",
    ambitoSugerido: "medio_ambiente",
    ambitosSecundariosSugeridos: ["seguridad_laboral"],
    tipoEventoSugerido: "aspecto_ambiental",
    moduloPreguntasSugerido: "comunidad_terceros",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 6,
    palabrasClave: ["comunidad", "vecino", "tercero", "reclamo", "afectacion externa"],
    sinonimos: ["poblacion cercana", "colindante", "publico"],
    frasesFrecuentes: ["afecta a comunidad", "reclamo de vecino"],
    exclusiones: ["sin afectacion a terceros"],
    senalesElevanCriticidad: ["Afectacion externa.", "Queja o exposicion de terceros."],
    senalesPermitenCritico: ["Afectacion severa o masiva a terceros."],
    normativaProbable: ["Ley 19.300"],
    requiereRevisionManual: true,
  },
  {
    categoria: "rca_permisos_ambientales",
    familia: "RCA/permisos ambientales",
    ambitoSugerido: "medio_ambiente",
    ambitosSecundariosSugeridos: ["legal_documental"],
    tipoEventoSugerido: "desviacion_legal_documental",
    moduloPreguntasSugerido: "rca_permisos_ambientales",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 7,
    palabrasClave: ["rca", "resolucion de calificacion ambiental", "permiso ambiental", "compromiso ambiental"],
    sinonimos: ["condicion rca", "permiso sectorial", "pas ambiental"],
    frasesFrecuentes: ["incumplimiento rca", "permiso ambiental vencido"],
    exclusiones: ["permiso ambiental vigente"],
    senalesElevanCriticidad: ["Compromiso ambiental aplicable.", "Actividad en ejecucion."],
    senalesPermitenCritico: ["Incumplimiento con impacto ambiental real o notificacion obligatoria."],
    normativaProbable: ["RCA / permiso ambiental del proyecto", "Ley 19.300"],
    requiereRevisionManual: true,
  },
  {
    categoria: "condiciones_sanitarias_ambientales",
    familia: "Condiciones sanitarias y ambientales basicas",
    ambitoSugerido: "salud_ocupacional",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "condiciones_sanitarias_ambientales",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 5,
    palabrasClave: ["banos", "agua potable", "ventilacion", "iluminacion", "temperatura", "higiene", "comedor"],
    sinonimos: ["servicios higienicos", "condicion sanitaria", "condiciones ambientales"],
    frasesFrecuentes: ["falta agua potable", "ventilacion deficiente"],
    exclusiones: ["condicion sanitaria normal"],
    senalesElevanCriticidad: ["Exposicion prolongada.", "Afecta grupo de trabajadores."],
    senalesPermitenCritico: ["Condicion sanitaria severa con riesgo inmediato para salud."],
    normativaProbable: ["DS 594"],
  },
  {
    categoria: "conductas_inseguras",
    familia: "Conductas inseguras",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "acto_inseguro",
    moduloPreguntasSugerido: "conductas_inseguras",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 6,
    palabrasClave: ["acto inseguro", "conducta insegura", "trabajador realiza", "intervencion no autorizada", "no respeta procedimiento"],
    sinonimos: ["accion insegura", "desviacion conductual", "operacion insegura"],
    frasesFrecuentes: ["trabajador sin epp", "persona cruza zona segregada"],
    exclusiones: ["condicion subestandar sin conducta"],
    senalesElevanCriticidad: ["Actividad en ejecucion.", "Exposicion directa."],
    senalesPermitenCritico: ["Conducta activa frente a energia o peligro fatal."],
    normativaProbable: ["Ley 16.744", "DS 44"],
  },
  {
    categoria: "condiciones_subestandar",
    familia: "Condiciones subestandar",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "condicion_subestandar",
    moduloPreguntasSugerido: "condiciones_subestandar",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 4,
    palabrasClave: ["condicion subestandar", "condicion insegura", "falta de control", "control parcial"],
    sinonimos: ["desviacion operacional", "condicion peligrosa"],
    frasesFrecuentes: ["condicion sin control", "barrera insuficiente"],
    exclusiones: ["condicion controlada"],
    senalesElevanCriticidad: ["Exposicion de personas.", "Controles inexistentes."],
    senalesPermitenCritico: ["Senal critica real asociada a peligro fatal."],
    normativaProbable: ["Ley 16.744", "DS 44"],
  },
  {
    categoria: "casi_accidentes",
    familia: "Casi accidentes",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "casi_accidente",
    moduloPreguntasSugerido: "casi_accidentes",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 8,
    palabrasClave: ["casi accidente", "near miss", "amago", "por poco", "cuasi accidente"],
    sinonimos: ["evento sin lesion", "incidente potencial"],
    frasesFrecuentes: ["por poco golpea", "casi cae"],
    exclusiones: ["simulacro"],
    senalesElevanCriticidad: ["Potencial grave.", "Repeticion probable."],
    senalesPermitenCritico: ["Casi accidente con potencial fatal claro y exposicion real."],
    normativaProbable: ["Ley 16.744", "DS 44"],
    requiereRevisionManual: true,
  },
  {
    categoria: "incidentes_con_sin_lesion",
    familia: "Incidentes con o sin lesion",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "incidente",
    moduloPreguntasSugerido: "incidentes_con_sin_lesion",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 9,
    palabrasClave: ["incidente", "accidente", "lesion", "golpeado", "corte", "caida ocurrida", "atencion medica"],
    sinonimos: ["evento con lesion", "dano a persona", "primeros auxilios"],
    frasesFrecuentes: ["trabajador lesionado", "accidente con lesion"],
    exclusiones: ["sin lesion ni exposicion"],
    senalesElevanCriticidad: ["Lesion real.", "Potencial grave."],
    senalesPermitenCritico: ["Lesion grave/fatal o potencial fatal confirmado."],
    normativaProbable: ["Ley 16.744"],
    requiereRevisionManual: true,
  },
  {
    categoria: "mixto_seguridad_ambiente_legal",
    familia: "Hallazgos mixtos seguridad + ambiente + legal",
    ambitoSugerido: "mixto",
    ambitosSecundariosSugeridos: ["seguridad_laboral", "medio_ambiente", "legal_documental"],
    tipoEventoSugerido: "otro",
    moduloPreguntasSugerido: "mixto_seguridad_ambiente_legal",
    criticidadBaseSugerida: "ALTO",
    topeCriticidad: "CRITICO",
    prioridad: 9,
    palabrasClave: ["seguridad ambiente legal", "mixto", "derrame sin permiso", "trabajo critico sin permiso con derrame"],
    sinonimos: ["hallazgo mixto", "multiples ambitos", "seguridad y ambiente"],
    frasesFrecuentes: ["falta de permiso y derrame", "exposicion de personas y contaminacion"],
    exclusiones: ["ambito unico claro"],
    senalesElevanCriticidad: ["Mas de un ambito con exposicion real.", "Control insuficiente."],
    senalesPermitenCritico: ["Senal critica real en seguridad o impacto ambiental no contenido."],
    normativaProbable: ["Ley 16.744", "DS 44", "Ley 19.300"],
    requiereRevisionManual: true,
  },
  {
    categoria: "otro_indeterminado",
    familia: "Otro o indeterminado",
    ambitoSugerido: "seguridad_laboral",
    tipoEventoSugerido: "otro",
    moduloPreguntasSugerido: "otro_indeterminado",
    criticidadBaseSugerida: "MEDIO",
    topeCriticidad: "ALTO",
    prioridad: 0,
    palabrasClave: [],
    frasesFrecuentes: [],
    exclusiones: [],
    senalesElevanCriticidad: ["Se requiere clasificacion manual."],
    senalesPermitenCritico: ["Solo con senal critica confirmada."],
    normativaProbable: ["Normativa probable asociada pendiente de clasificacion"],
    requiereRevisionManual: true,
  },
];
